spring:
  application:
    name: capstone-api
  profiles:
    active: local

server:
  port: ${API_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info

jwt:
  #최소 32글자 이상의 랜덤 문자열
  secret: capstone-ai-annotation-platform-super-secret-key-2026-very-long
  #토근 유효시간(밀리초)
  expiration: 864000003 # 24시간 (24 * 60 * 60 * 1000)